version: "3"
services:
  appserver1:
    image: "conatel/appserver1"
    container_name: "appserver1"
    depends_on: [dbserver1]
    environment:
      - MYSQL_DATABASE=grupo1
      - DMZ_IP=172.18.0.3
      - BACKEND_IP=172.18.1.3
    networks:
      dmz:
        ipv4_address: ${DMZ_IP}
      backend:
        ipv4_address: ${BACKEND_IP}
  appserver2:
    image: "conatel/appserver2"
    container_name: "appserver2"
    networks:
      dmz:
        ipv4_address: 172.18.0.4
  webserver1:
    image: "conatel/webserver1"
    container_name: "webserver1"
    environment:
      - DMZ_IP=172.18.0.2
    ports:
      - "80:80"
    networks:
      dmz:
        ipv4_address: ${DMZ_IP}
  webserver2:
    image: "conatel/webserver2"
    container_name: "webserver2"
    ports:
      - "8080:8080"
    networks:
      dmz:
        ipv4_address: 172.18.0.5
      backend:
        ipv4_address: 172.18.1.5
  dbserver1:
    image: "mysql"
    container_name: "dbserver1"
    environment:
      - MYSQL_DATABASE=grupo1
      - MYSQL_ROOT_PASSWORD=password
      - BACKEND_IP=172.18.1.2
    networks:
      backend:
        ipv4_address: ${BACKEND_IP}

networks:
  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
